### ISSUE TITLE
Site not working

### ISSUE THREAD

**Issue by PatelN123** [oxidizer-rs/website#163]
// TODO: site unavailable on 12/31/2021

This site is part of the Docusaurus showcase, and it seems that the site is down.

For reference: [facebook/docusaurus@c963f12](https://github.com/facebook/docusaurus/pull/6231/commits/c963f120e9ab96389a0dc9cfe2641d9bf25edea0)

**Comment by vandreleal** [comment]
Hi @PatelN123, thanks for letting us know. I've updated the URL in the following PR https://github.com/facebook/docusaurus/pull/6242

**Comment by PatelN123** [comment]
Awesome!
